config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'

  get 'next', to: 'visitors#random_corgi', as: 'next_corgi'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController

  def index
    @corgi = ImgurService.get_random_corgi
  end

  def random_corgi
    render json: ImgurService.get_random_corgi
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Corgistream" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Corgi Stream" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<h5>
Corgis!
</h5>
<h4>
Corgis!
</h4>
<h1>
Corgis!
</h1>

app/views/visitors/index.html.erb
<h3>Corgi Stream!!!</h3>
<h4 id="corgi-title" class="text-center">Loading...</h4>
<div id="big-corgi"></div>
<p id="corgi-description" class="text-center lead"></p>
<div class="text-center">
  <button id="next-button" onclick="nextCorgi('<%= next_corgi_path %>')">Loading...</button>
  <button id="auto-button" onclick="toggleAuto('<%= next_corgi_path %>')">Auto Corg!</button>
</div>


<script>
  setCorgi("<%= @corgi["link"] %>", "<%= raw j @corgi["title"] %>", "<%= raw j @corgi["description"] %>");

  $(document).ready(function () {
    if (window.corgiTimer) 
      clearInterval(window.corgiTimer);
  });
</script>